### ISSUE TITLE
License - correct attribution

### ISSUE THREAD

**Issue by kuahyeow** [stolen-ruby/conflict_free_schema#2]
Hi, I am an engineer working in GitLab. First of all, thanks for this amazing work ! I agree there are many things we could do better to publish as separate gems, and also upstream such as Rails (and hey, it's already open-source)

About the license file, I notice the copyright notice omits GitLab who was the original author from the original copyright notice in https://gitlab.com/gitlab-org/gitlab/-/blob/d57b6aef6d816e028d855c36944c6559b22b9f9f/LICENSE. Can you please update to include `GitLab B.V.` as an author in the copyright notice as well ? Thanks!

**Comment by kuahyeow** [comment]
Also, while I am here - there has been a big update to the library to support multiple databases - https://gitlab.com/gitlab-org/gitlab/-/merge_requests/64884. Maybe it's something you are interested in ?

**Comment by rwojsznis** [comment]
Hey @kuahyeow 👋

sorry for late reply, almost missed you issue to be honest (catching up after vacations); let me know if ad4a7be51c819977cd7cb1e6ce8c0ee6325d563f looks good to you!

> Maybe it's something you are interested in ?

Looks like pretty sweet addition! ❤️ I will try to take a look at that MR in upcoming weeks, thanks for heads up!

And I _do_ wish such feature was already bundled into, um, more _official_ gem or Rails itself! 😄

**Comment by kuahyeow** [comment]
Thanks @rwojsznis for the awesome, and quick response ! https://github.com/stolen-ruby/conflict_free_schema/commit/ad4a7be51c819977cd7cb1e6ce8c0ee6325d563f looks good to me 👍
