### ISSUE TITLE
recursive search for migrations within specific folders

### ISSUE THREAD

**Issue by Ivanov-Anton** [stolen-ruby/conflict_free_schema#3]
Hellow, when I am trying to use your gem, then not all migration files are found within the folder `db/migrate`
I have the same subfolders as 1.0, 2.0 e.t.c.

I would like to search for migration files not only inside `db/migrate/*` but do a recursive search for migrations within this folder.
Something like that `db/migrate/**/*`.

**Comment by rwojsznis** [comment]
Hey there @Ivanov-Anton 👋 thank you for your contribution in #4 

Can you please describe how do you structure your migrations and what is your exact use case? 🤔 

From the description I assume you put (sub)folders in `db/migrate` and/or in `db/post_migrate` directories, correct? Could you explain what's the reason behind it and maybe provide some real-life examples? Thank you!

**Comment by Ivanov-Anton** [comment]
@rwojsznis, For example, we release 4.0 new version and place corresponding migrations in db/migrate/4.0/ folder.

**Comment by rwojsznis** [comment]
I see, thanks for explanation! If don't break current behavior I don't see why not to add it - let's continue discussion in #4
